# Generated by Django 4.1.2 on 2023-04-21 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupstat',
            name='password',
        ),
    ]
