# Generated by Django 4.1.2 on 2023-04-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Roles', models.CharField(max_length=50)),
                ('Salary', models.CharField(max_length=50)),
                ('TimeStart', models.DateTimeField()),
                ('TimeEnd', models.DateTimeField()),
            ],
        ),
    ]
