# Generated by Django 4.1.2 on 2023-04-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
