# Generated by Django 4.1.2 on 2023-04-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='resume',
            field=models.FileField(default=None, max_length=250, upload_to='dashboard/'),
        ),
    ]
