# Generated by Django 4.1.2 on 2023-04-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_job_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='branch',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
