# Generated by Django 4.1.2 on 2023-04-28 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_job_branch_alter_job_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='inc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('val', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='branch',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
