# Generated by Django 4.1.2 on 2023-04-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_inc_name_alter_inc_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inc',
            name='val',
            field=models.IntegerField(default='', primary_key=True, serialize=False),
        ),
    ]
