# Generated by Django 4.1.2 on 2023-04-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_inc_val'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='compname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
