# Generated by Django 4.1.2 on 2023-04-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_job_compname'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='roles',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
