# Generated by Django 4.1.2 on 2023-04-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_job_roles_job_salary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
