# Generated by Django 4.1.2 on 2023-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_companydata_poc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='resume',
            field=models.FileField(default=None, max_length=250, upload_to=''),
        ),
    ]
