# Generated by Django 4.1.2 on 2023-04-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_appl_delete_appli'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appl',
        ),
    ]
